[package]
name = "vibe-survival-game"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "1.1"
log = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
noise = "0.8" 
jsonwebtoken = "8" # Or the latest compatible version
