use crate::items::{ItemDefinition, ItemCategory, CostIngredient};
use crate::models::{EquipmentSlotType, TargetType};

pub fn get_initial_item_definitions() -> Vec<ItemDefinition> {
    let initial_items = vec![
        // --- BASE RESOURCES ---
        ItemDefinition {
            id: 0,
            name: "Wood".to_string(),
            description: "A sturdy piece of wood. Good for fuel.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "wood.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: Some(5.0),
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone".to_string(),
            description: "A chunk of rock.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "stone.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(30),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Plant Fiber".to_string(),
            description: "Fibrous material from plants, used for making cloth or as a quick, inefficient fuel.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "plant_fiber.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: Some(1.5),
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth".to_string(),
            description: "Woven fabric, used for basic clothing.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "cloth.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 5 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(1),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Charcoal".to_string(),
            description: "Residue from burnt wood. Useful for crafting.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "charcoal.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Bone Fragments".to_string(),
            description: "Sharp fragments of bone. Useful for crafting arrowheads.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "bone_fragments.png".to_string(),
            is_stackable: true,
            stack_size: 500,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Animal Bone".to_string(),
            description: "A sturdy animal bone. Useful for crafting basic tools and weapons.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "bone.png".to_string(),
            is_stackable: true,
            stack_size: 250,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Animal Fat".to_string(),
            description: "A slippery piece of animal fat. Can be rendered for fuel or used in crafting.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "animal_fat.png".to_string(),
            is_stackable: true,
            stack_size: 100,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: Some(10.0),
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: Some(15.0),
            cooked_item_def_name: Some("Tallow".to_string()),
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Human Skull".to_string(),
            description: "The surprisingly intact skull of a former human. Grim, but effective in a pinch.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "skull.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(5),
            primary_target_damage_max: Some(10),
            primary_target_yield_min: Some(1),
            primary_target_yield_max: Some(2),
            primary_target_type: Some(TargetType::Tree),
            primary_yield_resource_name: Some("Wood".to_string()),
            secondary_target_damage_min: Some(3),
            secondary_target_damage_max: Some(6),
            secondary_target_yield_min: Some(1),
            secondary_target_yield_max: Some(1),
            secondary_target_type: Some(TargetType::Stone),
            secondary_yield_resource_name: Some("Stone".to_string()),
            pvp_damage_min: Some(30),
            pvp_damage_max: Some(30),
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: Some(2.0),
        },
        ItemDefinition {
            id: 0,
            name: "Bone Club".to_string(),
            description: "A heavy club made from a large bone and bindings. Good for crushing.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "bone_club.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(8),
            primary_target_damage_max: Some(15),
            primary_target_yield_min: Some(2),
            primary_target_yield_max: Some(4),
            primary_target_type: Some(TargetType::Tree),
            primary_yield_resource_name: Some("Wood".to_string()),
            secondary_target_damage_min: Some(5),
            secondary_target_damage_max: Some(10),
            secondary_target_yield_min: Some(1),
            secondary_target_yield_max: Some(3),
            secondary_target_type: Some(TargetType::Stone),
            secondary_yield_resource_name: Some("Stone".to_string()),
            pvp_damage_min: Some(25),
            pvp_damage_max: Some(25),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Bone Fragments".to_string(), quantity: 125 },
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(20),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: Some(0.8),
        },
        ItemDefinition {
            id: 0,
            name: "Bone Knife".to_string(),
            description: "A sharp knife crafted from bone. Quick but not very durable.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "bone_knife.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(3),
            primary_target_damage_max: Some(6),
            primary_target_yield_min: Some(1),
            primary_target_yield_max: Some(2),
            primary_target_type: Some(TargetType::Animal),
            primary_yield_resource_name: Some("Animal Hide".to_string()),
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(15),
            pvp_damage_max: Some(20),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Bone Fragments".to_string(), quantity: 50 },
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 5 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(10),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: Some(1.0),
            bleed_duration_seconds: Some(5.0),
            bleed_tick_interval_seconds: Some(1.0),
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: Some(0.5),
        },

        // --- TOOLS ---
        ItemDefinition {
            id: 0,
            name: "Stone Hatchet".to_string(),
            description: "A simple hatchet for chopping wood.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "wood_hatchet.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(25),
            primary_target_damage_max: Some(35),
            primary_target_yield_min: Some(25),
            primary_target_yield_max: Some(35),
            primary_target_type: Some(TargetType::Tree),
            primary_yield_resource_name: Some("Wood".to_string()),
            secondary_target_damage_min: Some(3),
            secondary_target_damage_max: Some(7),
            secondary_target_yield_min: Some(3),
            secondary_target_yield_max: Some(7),
            secondary_target_type: Some(TargetType::Stone),
            secondary_yield_resource_name: Some("Stone".to_string()),
            pvp_damage_min: Some(15),
            pvp_damage_max: Some(15),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 200 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 100 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(30),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(600),
            attack_interval_secs: Some(0.8),
        },
        ItemDefinition {
            id: 0,
            name: "Combat Ladle".to_string(),
            description: "A surprisingly sturdy ladle, ready for a culinary confrontation.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "combat_ladle.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(10),
            pvp_damage_max: Some(10),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 50 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(10),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: Some(1.0),
        },
        ItemDefinition {
            id: 0,
            name: "Stone Pickaxe".to_string(),
            description: "A simple pickaxe for breaking rocks.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "pick_axe.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(13),
            primary_target_damage_max: Some(22),
            primary_target_yield_min: Some(13),
            primary_target_yield_max: Some(22),
            primary_target_type: Some(TargetType::Stone),
            primary_yield_resource_name: Some("Stone".to_string()),
            secondary_target_damage_min: Some(3),
            secondary_target_damage_max: Some(7),
            secondary_target_yield_min: Some(3),
            secondary_target_yield_max: Some(7),
            secondary_target_type: Some(TargetType::Tree),
            secondary_yield_resource_name: Some("Wood".to_string()),
            pvp_damage_min: Some(17),
            pvp_damage_max: Some(17),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 200 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 100 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(30),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(600),
            attack_interval_secs: Some(1.2),
        },
        ItemDefinition {
            id: 0,
            name: "Rock".to_string(),
            description: "A basic tool for gathering.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "rock_item.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(3),
            primary_target_damage_max: Some(7),
            primary_target_yield_min: Some(3),
            primary_target_yield_max: Some(7),
            primary_target_type: Some(TargetType::Stone),
            primary_yield_resource_name: Some("Stone".to_string()),
            secondary_target_damage_min: Some(3),
            secondary_target_damage_max: Some(7),
            secondary_target_yield_min: Some(3),
            secondary_target_yield_max: Some(7),
            secondary_target_type: Some(TargetType::Tree),
            secondary_yield_resource_name: Some("Wood".to_string()),
            pvp_damage_min: Some(5),
            pvp_damage_max: Some(5),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Stone".to_string(), quantity: 5 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(1),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: Some(0.7),
        },
        ItemDefinition {
            id: 0,
            name: "Wooden Spear".to_string(),
            description: "A sharpened stick. Better than throwing rocks.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "spear.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(25),
            pvp_damage_max: Some(25),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 300 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(30),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: Some(2.0),
            bleed_duration_seconds: Some(8.0),
            bleed_tick_interval_seconds: Some(1.0),
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: Some(1.5),
        },
        ItemDefinition {
            id: 0,
            name: "Torch".to_string(),
            description: "Provides light and some warmth. Can be used as a makeshift weapon.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "torch.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(5),
            pvp_damage_max: Some(5),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 20 },
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(30),
            attack_interval_secs: Some(0.5),
        },
        ItemDefinition {
            id: 0,
            name: "Stone Spear".to_string(),
            description: "A basic spear tipped with sharpened stone. Has a longer reach and causes bleeding.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "stone_spear.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(35),
            pvp_damage_max: Some(35),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 300 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 100 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(30),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: Some(3.0),
            bleed_duration_seconds: Some(8.0),
            bleed_tick_interval_seconds: Some(1.0),
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(420),
            attack_interval_secs: Some(1.3),
        },

        // --- PLACEABLES ---
        ItemDefinition {
            id: 0,
            name: "Camp Fire".to_string(),
            description: "A place to cook food and stay warm.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "campfire.png".to_string(),
            is_stackable: true,
            stack_size: 5,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 25 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stash".to_string(),
            description: "A small, concealable stash for hiding items. Fewer slots than a box, but can be hidden.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "stash.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 5 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(10),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Wooden Storage Box".to_string(),
            description: "A simple container for storing items.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "wooden_storage_box.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 100 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Sleeping Bag".to_string(),
            description: "A rolled-up bag for sleeping outdoors. Sets a respawn point.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "sleeping_bag.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 25 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },

        // --- ARMOR (CLOTH SET) ---
        ItemDefinition {
            id: 0,
            name: "Cloth Hood".to_string(),
            description: "Basic head covering.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_hood.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Head),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 20 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(10),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: Some(0.01),
            warmth_bonus: Some(0.2),
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Shirt".to_string(),
            description: "Simple protection for the torso.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_shirt.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Chest),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 40 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: Some(0.01),
            warmth_bonus: Some(0.2),
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Pants".to_string(),
            description: "Simple protection for the legs.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_pants.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Legs),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 30 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: Some(0.01),
            warmth_bonus: Some(0.2),
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Gloves".to_string(),
            description: "Basic hand coverings.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_gloves.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Hands),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 15 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: Some(0.01),
            warmth_bonus: Some(0.2),
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Boots".to_string(),
            description: "Simple footwear.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_boots.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Feet),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 15 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: Some(0.01),
            warmth_bonus: Some(0.2),
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Cape".to_string(),
            description: "A simple cape made of cloth.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "burlap_cape.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Back),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 30 },
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(20),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: Some(0.01),
            warmth_bonus: Some(0.1),
            respawn_time_seconds: Some(420),
            attack_interval_secs: None,
        },
        
        // --- CONSUMABLES (Rebalanced and New) ---
        ItemDefinition {
            id: 0,
            name: "Mushroom".to_string(),
            description: "A raw mushroom. Edible, but provides little sustenance, and makes you thirsty.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "mushroom.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(3.0),      
            consumable_hunger_satiated: Some(5.0),  
            consumable_thirst_quenched: Some(-2.0), 
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: Some(20.0), 
            cooked_item_def_name: Some("Cooked Mushroom".to_string()),
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(180),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cooked Mushroom".to_string(),
            description: "A tasty cooked mushroom. More filling.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "cooked_mushroom.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(10.0),     
            consumable_hunger_satiated: Some(20.0), 
            consumable_thirst_quenched: Some(2.0),  
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: Some(30.0), 
            cooked_item_def_name: Some("Burnt Mushroom".to_string()),
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(240),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Burnt Mushroom".to_string(),
            description: "Oops, cooked it too long. Barely edible.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "burnt_mushroom.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(-2.0),    
            consumable_hunger_satiated: Some(2.0),  
            consumable_thirst_quenched: Some(-10.0),
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(60),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Corn".to_string(),
            description: "Raw corn. A bit tough and not very satisfying.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "corn.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(2.0),
            consumable_hunger_satiated: Some(10.0),
            consumable_thirst_quenched: Some(5.0), 
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: Some(25.0),
            cooked_item_def_name: Some("Cooked Corn".to_string()),
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(180),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cooked Corn".to_string(),
            description: "Sweet and satisfying. A good source of energy.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "cooked_corn.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(15.0),
            consumable_hunger_satiated: Some(40.0), 
            consumable_thirst_quenched: Some(10.0), 
            consumable_stamina_gain: None,          
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: Some(35.0), 
            cooked_item_def_name: Some("Burnt Corn".to_string()),
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(240),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Burnt Corn".to_string(),
            description: "Charred and disappointing. Mostly carbon now.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "burnt_corn.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(-5.0),
            consumable_hunger_satiated: Some(5.0),
            consumable_thirst_quenched: Some(-15.0),
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(60),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Pumpkin".to_string(),
            description: "A large, raw pumpkin. Can be cooked.".to_string(),
            category: ItemCategory::Consumable, 
            icon_asset_name: "pumpkin.png".to_string(), 
            is_stackable: true,
            stack_size: 5, 
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(5.0),
            consumable_hunger_satiated: Some(15.0),
            consumable_thirst_quenched: Some(10.0), 
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: Some(60.0), 
            cooked_item_def_name: Some("Cooked Pumpkin".to_string()),
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cooked Pumpkin".to_string(),
            description: "Soft, sweet, and nutritious cooked pumpkin chunks.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "cooked_pumpkin.png".to_string(), 
            is_stackable: true,
            stack_size: 10, 
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(20.0),
            consumable_hunger_satiated: Some(50.0), 
            consumable_thirst_quenched: Some(15.0), 
            consumable_stamina_gain: Some(5.0),    
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: Some(45.0), 
            cooked_item_def_name: Some("Burnt Pumpkin".to_string()),
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(360),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Burnt Pumpkin".to_string(),
            description: "A blackened, mushy mess. Not recommended.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "burnt_pumpkin.png".to_string(), 
            is_stackable: true,
            stack_size: 10,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(-10.0),
            consumable_hunger_satiated: Some(5.0),
            consumable_thirst_quenched: Some(-5.0),
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(60),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Bandage".to_string(),
            description: "A simple bandage to patch up wounds. Stops bleeding and restores health.".to_string(), 
            category: ItemCategory::Tool,
            icon_asset_name: "bandage.png".to_string(),
            is_stackable: true,
            stack_size: 10,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![CostIngredient { item_name: "Cloth".to_string(), quantity: 2 }]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(3), 
            consumable_health_gain: Some(25.0), 
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: Some(5.0),
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: Some(300),
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Hunting Bow".to_string(),
            description: "A basic, silent ranged weapon suitable for early-game hunting and combat.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "bow.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(50),
            pvp_damage_max: Some(50),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 200 },
                CostIngredient { item_name: "Cloth".to_string(), quantity: 50 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(30),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: Some(1.0),
        },
        ItemDefinition {
            id: 0,
            name: "Wooden Arrow".to_string(),
            description: "The standard arrow with balanced damage and range and minimal bleed damage.".to_string(),
            category: ItemCategory::Ammunition,
            icon_asset_name: "wooden_arrow.png".to_string(),
            is_stackable: true,
            stack_size: 50,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 25 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(2),
            crafting_time_secs: Some(1),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: Some(0.5),
            bleed_duration_seconds: Some(4.0),
            bleed_tick_interval_seconds: Some(1.0),
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Bone Arrow".to_string(),
            description: "Features a larger arrowhead, making it easier to hit targets but deals slightly less damage and no bleed.".to_string(),
            category: ItemCategory::Ammunition,
            icon_asset_name: "bone_arrow.png".to_string(),
            is_stackable: true,
            stack_size: 50,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 25 },
                CostIngredient { item_name: "Bone Fragments".to_string(), quantity: 25 },
            ]),
            crafting_output_quantity: Some(2),
            crafting_time_secs: Some(3),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
            bleed_damage_per_tick: None,
            bleed_duration_seconds: None,
            bleed_tick_interval_seconds: None,
            cook_time_secs: None,
            cooked_item_def_name: None,
            damage_resistance: None,
            warmth_bonus: None,
            respawn_time_seconds: None,
            attack_interval_secs: None,
        },
    ];

    initial_items
}
